name: Install Python

on:
  workflow_dispatch:
    

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      run: |
        sudo df -hT
