name: System Information

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  system_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display lsblk (Block Devices)
        run: |
          echo "Listing block devices with lsblk:"
          sudo mkdir /mnt/l
          sudo mount /dev/sdc1 /mnt/l

      - name: Display Number of CPU Cores
        run: |
          echo "Number of CPU cores:"
          nproc

      - name: Display Memory Usage
        run: |
          echo "Displaying memory usage with free -h:"
          free -h
